version: '2'

x-peer-defaults: &peer-defaults
  extends:
    file: peer-base.yaml
    service: peer-base
  environment:
    - GODEBUG=netdns=go
  volumes:
    - /var/run/:/host/var/run/

x-org1-defaults: &org1-defaults
  <<: *peer-defaults
  environment:
    - CORE_PEER_LOCALMSPID=Org1MSP
  volumes:
    - ../crypto-config/peerOrganizations/org1.personal-network.com/peers/peer0.org1.personal-network.com/msp:/etc/hyperledger/fabric/msp:rw
    - ../crypto-config/peerOrganizations/org1.personal-network.com/peers/peer0.org1.personal-network.com/tls:/etc/hyperledger/fabric/tls:rw

x-org2-defaults: &org2-defaults
  <<: *peer-defaults
  environment:
    - CORE_PEER_LOCALMSPID=Org2MSP
  volumes:
    - ../crypto-config/peerOrganizations/org2.personal-network.com/peers/peer0.org2.personal-network.com/msp:/etc/hyperledger/fabric/msp:rw
    - ../crypto-config/peerOrganizations/org2.personal-network.com/peers/peer0.org2.personal-network.com/tls:/etc/hyperledger/fabric/tls:rw

services: 
  orderer.personal-network.com: 
    container_name: orderer.personal-network.com
    image: hyperledger/fabric-orderer:2.2.9 
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/gopath/fabric-samples/personal-network/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts/genesis.block:/opt/gopath/fabric-samples/personal-network/channel-artifacts/genesis.block
      - ../crypto-config/ordererOrganizations/personal-network.com/orderers/orderer.personal-network.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/personal-network.com/orderers/orderer.personal-network.com/tls/:/var/hyperledger/orderer/tls
      - orderer.personal-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org1.personal-network.com:
    <<: *org1-defaults
    container_name: peer0.org1.personal-network.com
    environment:
      - CORE_PEER_ID=peer0.org1.personal-network.com
      - CORE_PEER_ADDRESS=peer0.org1.personal-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.personal-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.personal-network.com:7051
    volumes:
      - peer0.org1.personal-network.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.org2.personal-network.com: 
    <<: *org2-defaults
    container_name: peer0.org2.personal-network.com
    environment: 
      - CORE_PEER_ID=peer0.org2.personal-network.com
      - CORE_PEER_ADDRESS=peer0.org2.personal-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.personal-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.personal-network.com:7051
    volumes:
      - peer0.org2.personal-network.com:/var/hyperledger/production
    ports: 
      - 9051:7051