OrdererOrgs: 
  - Name: OrderingService
    Domain: personal-network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.personal-network.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.personal-network.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

# cryptogen generate --config=crypto-config.yaml \
# --output=crypto-config